version: '2'
services:
  mariadb:
    image: mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bn_password
      - MARIADB_ROOT_PASSWORD=bn_password
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/var/lib/mysql'
  moodle:
    image: moodlehq/moodle-php-apache:8.3

    ports:
      - '8080:80'
      - '8443:443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bn_password
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle:/var/www/html'
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
  jobe:
    image: trampgeek/jobeinabox:latest
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
